// HELLO WORLD ACTIONS
export const HELLO_WORLD = 'HELLO_WORLD';
export const HELLO_WORLD_END = 'HELLO_WORLD_END';

// LOGIN ACTIONS
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// LOGIN REGISTER
export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';


// QUESTIONS ACTIONS
export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_ALL_QUESTIONS_ERROR = 'GET_ALL_QUESTIONS_ERROR';
